name: Enforce Branch Name

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  enforce_branch_name:
    runs-on: "k8s-native"
    container:
      image: "ubuntu:24.04"

    steps:
      - name: Check Branch Name
        shell: bash
        run: |
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          ./.husky/check-branch-name.sh $branch_name
