name: "Lint"

env:
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
  FOUNDRY_PROFILE: "full_test"
  EORACLE_CHAIN_ID: 42420

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: "k8s-native-eodata"
    container:
      image: "node:22-bullseye"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "21.x"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"
        with:
          version: "nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970"

      - name: "Install the Node.js dependencies"
        run: "npm install"

      - name: "Lint the code"
        run: "npm run lint"

      - name: "Add lint summary"
        run: |
          echo "## Lint result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
